### ISSUE TITLE
Symfony 2.7 issues

### ISSUE THREAD

**Issue by chandon** [domis86/TranslatorBundle#5]
Back to issue #2 again with the new 2.7 Symfony version, and some more issues...

1) Translator must implement TranslatorBagInterface (the solution given to this problem with the issue #2 is not a good solution, getCalalogue must really return an object, not null) 

2) Argument 2 passed to Domis86\TranslatorBundle\EventListener\TranslatorConsoleListener::__construct() must be an instance of Domis86\TranslatorBundle\Translation\Translator, instance of Symfony\Component\Translation\DataCollectorTranslator given

perhaps some more ?

**Comment by chandon** [comment]
Dead project ?

**Comment by domis86** [comment]
I will try to fix this issue in next few days. Sorry for delay - i was quite busy with project in my work lately...

**Comment by chandon** [comment]
@domis86 thanks, your bundle is pretty great (and not well known enough). I hope it'll work on Symfony 2.7 LTS !

**Comment by domis86** [comment]
@chandon https://github.com/domis86/TranslatorBundle/releases
please add to composer.json:
```
"domis86/translator-bundle": "~1.0"
```
and do:
```
composer update domis86/translator-bundle
```
If you have any problems just contact me :) Any feedback is appreciated. Sorry for a bit of delay in fixing this....

**Comment by chandon** [comment]
@domis86 Thanks a lot, it works like a charm on Symfony 2.7 ! Great job
